### ISSUE TITLE
Module breaks with wagtail 2.11+

### ISSUE THREAD

**Issue by felicemcc** [infoportugal/wagtail-modeltranslation#328]
Hello I have a site with wagtail 2.10.2 but as soon as I pass to wagtail 2.11+ The wagtail-modeltranslation (0.10.15) module breaks, since the hooks are not called in the same fashion anymore.

I tried to make some changes, solved some issues and others appear, would you please take a look since I have not much knowledge of this code requirements for the moment.

Best regards

**Comment by perepicornell** [comment]
Same here:
```
  File "/usr/local/lib/python3.8/site-packages/wagtail_modeltranslation/wagtail_hooks.py", line 30, in <module>
    from wagtail.wagtailcore import hooks
ModuleNotFoundError: No module named 'wagtail.wagtailcore'
```

I tried downgrading to Wagtail 2.10.2 and yes, it's not throwing the error.

**Comment by perepicornell** [comment]
Sorry now I see there's an older ticket: https://github.com/infoportugal/wagtail-modeltranslation/issues/318

**Comment by DiogoMarques29** [comment]
Fixed in latest release v0.10.16

**Comment by perepicornell** [comment]
Is it working for you?
I just updated and crashes with:

```
Django Version: 3.1.5
Python Version: 3.8.5
Installed Applications:
['wagtail_modeltranslation',
 'wagtail_modeltranslation.makemigrations',
 'wagtail_modeltranslation.migrate',
 'apps.cms',
 'apps.users',
 'wagtail.contrib.forms',
 'wagtail.contrib.redirects',
 'wagtail.embeds',
 'wagtail.sites',
 'wagtail.users',
 'wagtail.snippets',
 'wagtail.documents',
 'wagtail.images',
 'wagtail.search',
 'wagtail.admin',
 'wagtail.core',
 'taggit',
 'modelcluster',
 'django.contrib.postgres',
 'django.contrib.admin',
 'grappelli',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'wagtail.contrib.redirects.middleware.RedirectMiddleware']

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/wagtail/admin/urls/__init__.py", line 127, in wrapper
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/wagtail/admin/auth.py", line 193, in decorated_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/wagtail/admin/views/home.py", line 187, in home
    site_details = get_site_for_user(request.user)
  File "/usr/local/lib/python3.8/site-packages/wagtail/admin/navigation.py", line 36, in get_site_for_user
    root_site = root_page.get_site()
  File "/usr/local/lib/python3.8/site-packages/wagtail/core/models.py", line 1720, in get_site
    url_parts = self.get_url_parts()
  File "/usr/local/lib/python3.8/site-packages/wagtail/core/models.py", line 1595, in get_url_parts
    possible_sites = [
  File "/usr/local/lib/python3.8/site-packages/wagtail/core/models.py", line 1597, in <listcomp>
    for pk, path, url, language_code in self._get_site_root_paths(request)

Exception Type: ValueError at /admin_cms/
Exception Value: not enough values to unpack (expected 4, got 3)
```

That was in the project I'm working on. Then I created a whole new django and wagtail project from scratch until I had the initial migrations applied and I could access wagtail's admin.
Then I added the modeltranslation package and crashed exactly the same way.

I'm using:
```
python = "^3.8"
django = "^3.1.5"
psycopg2-binary = "^2.8.6"
django-environ = "^0.4.5"
gunicorn = "^20.0.4"
django-grappelli = "^2.14.3"
django-constance = {extras = ["database"], version = "^2.8.0"}
django-maintenance-mode = "^0.15.1"
whitenoise = "^5.2.0"
wagtail = "^2.11.3"
wagtail-modeltranslation = "^0.10.16"
```

**Comment by perepicornell** [comment]
I just realized I can access anywhere in the admin area (settings, images, documents, etc.) but not the main page or the Pages section.

**Comment by DiogoMarques29** [comment]
hello @perepicornell 
there was a bug in out patching - _get_site_root_paths
It's fixed now in version 0.10.17, give it a try!
Cheers

**Comment by perepicornell** [comment]
like a charm!!
Thank you

Missatge de Diogo Marques <notifications@github.com> del dia dj., 21 de
gen. 2021 a les 12:02:

**Comment by jhnbkr** [comment]
I am still experiencing issues with Wagtail 2.11.x and wagtail-modeltranslation 0.101.17 when I hit the root admin page.

```
ValueError at /admin/
not enough values to unpack (expected 4, got 3)
Request Method:     GET
Request URL:        http://localhost:8000/admin/
Django Version:     3.1.5
Exception Type:     ValueError
Exception Value:	not enough values to unpack (expected 4, got 3)
Exception Location: /Users/john/Projects/wagtail-boilerplate/venv/lib/python3.8/site-packages/wagtail/core/models.py, line 1597, in <listcomp>
Python Executable:  /Users/john/Projects/wagtail-boilerplate/venv/bin/python
Python Version:     3.8.5
Python Path: [
    '/Users/john/Projects/wagtail-boilerplate',
    '/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev',
    '/Users/john/Projects/wagtail-boilerplate',
    '/Users/john/Projects/wagtail-boilerplate/project',
    '/Applications/PyCharm.app/Contents/plugins/python/helpers/pycharm_display',
    '/Applications/PyCharm.app/Contents/plugins/python/helpers/third_party/thriftpy',
    '/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev',
    '/Users/john/Library/Caches/JetBrains/PyCharm2020.3/cythonExtensions',
    '/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python38.zip',
    '/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8',
    '/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload',
    '/Users/john/Projects/wagtail-boilerplate/venv/lib/python3.8/site-packages',
    '/Applications/PyCharm.app/Contents/plugins/python/helpers/pycharm_matplotlib_backend'
]
Server time:        Fri, 22 Jan 2021 22:04:38 +0000
```

I have purged my virtual environment and cached fields. My project is a boilerplate setup and very minimal. I have also verified 0.10.17 is installed.

```
(venv) john@puter:Projects/wagtail-boilerplate ‹master*›$ pip show wagtail-modeltranslation
Name: wagtail-modeltranslation
Version: 0.10.17
Summary: Translates Wagtail CMS models using a registration approach.
Home-page: https://github.com/infoportugal/wagtail-modeltranslation
Author: InfoPortugal, S.A.
Author-email: suporte24@infoportugal.pt
License: New BSD
Location: /Users/john/Projects/wagtail-boilerplate/venv/lib/python3.8/site-packages
Requires: django-modeltranslation, wagtail
Required-by: 

```

My project is running on Python 3.8.5 with the following requirements

```
Django==3.1.5
Pillow==8.1.0
boto3==1.16.59
dj-database-url==0.5.0
django-cors-headers==3.6.0
django-environ==0.4.5
django-heroku==0.3.1
django-storages==1.11.1
django_redis==4.12.1
gunicorn==20.0.4
psycopg2-binary==2.8.6
redis==3.5.3
requests==2.25.1
sentry-sdk==0.19.5
wagtail==2.11.3
wagtail-modeltranslation==0.10.17
whitenoise==5.2.0
```
